#  Add 'UI' label to all PRs that touch ts / tsx files in the 'src' directory.
"UI":
  - "frontend/src/**/*.{ts,tsx,css}"

# Add 'backend' label to all PRs that touch json / py files in the 'raven' directory.
"backend":
  - "raven/**/*.{json,py}"
