/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        overlay: 'var(--color-overlay)',
        panel: {
          solid: 'var(--color-panel-solid)',
          translucent: 'var(--color-panel-translucent)',
        },
        surface: 'var(--color-surface)',
        transparent: 'var(--color-transparent)',
        gray: {
          1: 'var(--gray-1)',
          2: 'var(--gray-2)',
          3: 'var(--gray-3)',
          4: 'var(--gray-4)',
          5: 'var(--gray-5)',
          6: 'var(--gray-6)',
          7: 'var(--gray-7)',
          8: 'var(--gray-8)',
          9: {
            DEFAULT: 'var(--gray-9)',
            contrast: 'var(--gray-9-contrast)',
          },
          10: 'var(--gray-10)',
          11: 'var(--gray-11)',
          12: 'var(--gray-12)',
        },
        slate: {
          1: 'var(--slate-1)',
          2: 'var(--slate-2)',
          3: 'var(--slate-3)',
          4: 'var(--slate-4)',
          5: 'var(--slate-5)',
          6: 'var(--slate-6)',
          7: 'var(--slate-7)',
          8: 'var(--slate-8)',
          9: {
            DEFAULT: 'var(--slate-9)',
            contrast: 'var(--slate-9-contrast)',
          },
          10: 'var(--slate-10)',
          11: 'var(--slate-11)',
          12: 'var(--slate-12)',
        },
        accent: {
          1: 'var(--accent-1)',
          2: 'var(--accent-2)',
          3: 'var(--accent-3)',
          4: 'var(--accent-4)',
          5: 'var(--accent-5)',
          6: 'var(--accent-6)',
          7: 'var(--accent-7)',
          8: 'var(--accent-8)',
          9: {
            DEFAULT: 'var(--accent-9)',
            contrast: 'var(--accent-9-contrast)',
          },
          10: 'var(--accent-10)',
          11: 'var(--accent-11)',
          12: 'var(--accent-12)',
          a1: 'var(--accent-a1)',
          a2: 'var(--accent-a2)',
          a3: 'var(--accent-a3)',
          a4: 'var(--accent-a4)',
          a5: 'var(--accent-a5)',
          a6: 'var(--accent-a6)',
          a7: 'var(--accent-a7)',
          a8: 'var(--accent-a8)',
          a9: {
            DEFAULT: 'var(--accent-a9)',
            contrast: 'var(--accent-a9-contrast)',
          },
          a10: 'var(--accent-a10)',
          a11: 'var(--accent-a11)',
          a12: 'var(--accent-a12)',
        },
        iris: {
          1: 'var(--iris-1)',
          2: 'var(--iris-2)',
          3: 'var(--iris-3)',
          4: 'var(--iris-4)',
          5: 'var(--iris-5)',
          6: 'var(--iris-6)',
          7: 'var(--iris-7)',
          8: 'var(--iris-8)',
          9: {
            DEFAULT: 'var(--iris-9)',
            contrast: 'var(--iris-9-contrast)',
          },
          10: 'var(--iris-10)',
          11: 'var(--iris-11)',
          12: 'var(--iris-12)',
        },
        red: {
          1: 'var(--red-1)',
          2: 'var(--red-2)',
          3: 'var(--red-3)',
          4: 'var(--red-4)',
          5: 'var(--red-5)',
          6: 'var(--red-6)',
          7: 'var(--red-7)',
          8: 'var(--red-8)',
          9: {
            DEFAULT: 'var(--red-9)',
            contrast: 'var(--red-9-contrast)',
          },
          10: 'var(--red-10)',
          11: 'var(--red-11)',
          12: 'var(--red-12)',
        },
        green: {
          1: 'var(--green-1)',
          2: 'var(--green-2)',
          3: 'var(--green-3)',
          4: 'var(--green-4)',
          5: 'var(--green-5)',
          6: 'var(--green-6)',
          7: 'var(--green-7)',
          8: 'var(--green-8)',
          9: {
            DEFAULT: 'var(--green-9)',
            contrast: 'var(--green-9-contrast)',
          },
          10: 'var(--green-10)',
          11: 'var(--green-11)',
          12: 'var(--green-12)',
        }
      },
      borderRadius: {
        radius1: 'var(--radius-1)',
        radius2: 'var(--radius-2)',
        radius3: 'var(--radius-3)',
        radius4: 'var(--radius-4)',
        radius5: 'var(--radius-5)',
        radius6: 'var(--radius-6)',
      }
    },
  },
  darkMode: 'class',
  plugins: [
    require("tailwindcss-animate"),
  ],
  corePlugins: {
    preflight: false,
  }
}

