export interface SearchFilters {
    query?: string,
    channel_id?: string,
    owner?: string,
    parent_channel_id?: string,
    message_type?: string[] | string,
    file_type?: string[],
    channel_type?: string,
    is_direct_message?: 1 | 0 | null,
    is_thread?: 1 | 0 | null,
    is_thread_message?: 1 | 0 | null,
    is_bot_message?: 1 | 0 | null,
    saved?: 1 | 0 | null,
    is_pinned?: 1 | 0 | null,
    bot?: string,
    poll_id?: string,
    has_link?: 1 | 0 | null,
    has_reactions?: 1 | 0 | null,
    mentions?: string,
    mentions_me?: 1 | 0 | null,
}
